baseURL = "https://blog.dataforce.org.uk/"
languageCode = "en-gb"
title = "blog.dataforce.org.uk"
# theme = "material"
theme = "Shane2022"
# disablePathToLower = true
# enableGitInfo = true
enableRobotsTXT = true
disableKinds = ['taxonomy', 'section']
ignoreErrors = ["error-disable-taxonomy"]

[markup]
	[markup.highlight]
		codeFences = true
		# style = "vs"
		noClasses = false
	[markup.goldmark.renderer]
		unsafe = true

# See: https://github.com/tdewolff/minify/issues/469
[minify]
  [minify.tdewolff]
    [minify.tdewolff.js]
      keepVarNames = true

[params]
	# headerimg = "/wp-content/uploads/2016/05/header.png"
	headerimg = "/header.png"
	subtitle = "Dataforce's Blog"

	[params.profile]
		show = true
		image = "/wp-content/uploads/2016/05/ShaneNewColour.png"
		name = "Shane Mc Cormack"
		description = "Linux using, open source programming, network engineer."
		email = "shanemcc@gmail.com"
		twitter = "Dataforce"
		facebook = "Dataforce"
		github = "ShaneMcC"
		linkedin = "shanemccormack"

	[[params.sidebar]]
		link = "http://www.dfbnc.com/"
		name = "DFBnc"
		description = "– My IRC Bouncer"

	[[params.sidebar]]
		link = "https://www.dmdirc.com/"
		name = "DMDirc"
		description = "– The intelligent IRC Client"

	[[params.sidebar]]
		link = "https://cadence.net.uk/"
		name = "Cadence"
		description = "– My current employer."

	[[params.sidebar]]
		link = "/index/"
		name = "All posts"
		description = "– All posts on this site"

[taxonomies]
	category = "category"
	series = "series"
