baseURL = "https://blog.dataforce.org.uk/"
languageCode = "en-gb"
title = "blog.dataforce.org.uk"
theme = "material"
disablePathToLower = true

[params]
  headerimg = "/wp-content/uploads/2016/05/header.png"
  subtitle = "Dataforce's Blog"

[params.profile]
  show = true
  image = "/wp-content/uploads/2016/05/ShaneNewColour.png"
  name = "Shane Mc Cormack"
  description = "Linux using, open source programming, network engineer."
  email = "shanemcc@gmail.com"
  twitter = "Dataforce"
  facebook = "Dataforce"
  github = "ShaneMcC"
  linkedin = "shanemccormack"

[[params.sidebar]]
  link = "http://www.dfbnc.com/"
  name = "DFBnc"
  description = "– My IRC Bouncer"

[[params.sidebar]]
  link = "http://www.dmdirc.com/"
  name = "DMDirc"
  description = "– The intelligent IRC Client"

[[params.sidebar]]
  link = "http://www.melbourne.co.uk/"
  name = "Melbourne Server Hosting"
  description = "– My current employer."

[taxonomies]
  category = "category"
